#!/usr/bin/perl -w

use strict;
use DBI;
use DBD::Pg;
use Getopt::Long;

my $locale = undef;
GetOptions("locale=s" => \$locale);

my @skills = ('reading','writing','listening');

unless (defined($locale)) {
    print "Usage: uploadcrowdinsastatements --locale=eng_gb\n";
    exit 0;
}

my $dbh = DBI->connect("dbi:Pg:dbname=DIALANG", 'dialangadmin', 'dialangadmin', {AutoCommit => 0});

foreach my $skill (@skills) {
    my $texts = $dbh->selectall_arrayref("SELECT * FROM sa_statements WHERE locale = '$locale' AND skill = '$skill'");
    my $xml = qq(<?xml version="1.0" encoding="utf-8"?>\n);
    $xml .= "<resources>\n";
    foreach my $row (@$texts) {
        $xml .= "\t<string name=\"" . $row->[2] . "\">" . $row->[3] . "</string>\n"
    }
    $xml .= "</resources>\n";
    open(STATEMENTS,">$skill.$locale.xml");
    print STATEMENTS $xml;
    close(STATEMENTS);
}

$dbh->disconnect;

