#!/bin/sh

if [ $# -ne 1 ]
then
    echo "Usage: dumptexts eng_gb"
    exit 0
fi

scala -classpath build/classes/main\
:/Users/fisha/.m2/repository/postgresql/postgresql/9.1-901.jdbc4/postgresql-9.1-901.jdbc4.jar \
org.dialang.exporter.DisplayTextsDumper $1
